[package]
name = "byte-unit"
version = "4.0.17"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2021"
repository = "https://github.com/magiclen/byte-unit"
homepage = "https://magiclen.org/byte-unit"
keywords = ["byte", "unit", "kb", "mb", "gb"]
categories = ["no-std", "parser-implementations", "value-formatting"]
description = "A library for interaction with units of bytes."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[dependencies]
utf8-width = "0.1"

serde_dep = { package = "serde", version = "1", default-features = false, features = ["alloc"], optional = true }

[features]
default = ["std", "u128"]
serde = ["alloc", "serde_dep"]
std = ["serde_dep/std", "alloc"]
alloc = []
u128 = []
